use_frameworks!

platform :ios, '8.0'

target 'WCCategory_Example' do
  pod 'WCCategory', :path => '../'

  target 'WCCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
